### PR TITLE
Trims NPM packages

### LINKED ISSUE #2: docker compose build takes a long time
This is one of the solutions that builds particularly slowly. 
Following the guide, `docker compose build` takes >30min on a 2GB Pi4b. 
In addition to taking a long time, the display often freezes and it can be several minutes before keyboard/mouse inputs are visible. 
Notably for most of this time it is stuck on 
`RUN npm install`, which takes 10s of minutes.

Is there anything we can do about this? 
Do we make enough use of npm to justify such a big install? 
Are there any alternative packages that install quicker with similar functionality?

### PR DESCRIPTION
**Pull request by Greg-Hawkridge**
- fixes #2

### CODE REVIEW

**Comment by tobyaharris** [comment]
Testing:
`dev` was done first. System was stopped, pruned and dir deleted before directly cloning the bugfix branch. 
| Computer | operation | branch & time taken |
| --- | --- | --- |
| Pi5 8GB | `./setup_keys.sh` | 99.5s on `dev` <br> 102s on `bugfix/trim-packages` |
| Pi5 8GB | `docker compose build` | 147.4s on `dev` <br> 155.6s on `bugfix/trim-packages` |
| Pi5 8GB | `./start.sh` | 78.3s on `dev` <br> 76.0s on `bugfix/trim-packages` |
| Pi4 2GB | `./setup_keys.sh` | ?s on `dev` <br> ?s on `bugfix/trim-packages` |
| Pi4 2GB | `docker compose build` | ?s on `dev` <br> ?s on `bugfix/trim-packages` |
| Pi4 2GB | `./start.sh` | ?s on `dev` <br> ?s on `bugfix/trim-packages` |

1) I won't rush to say this has made a significant saving - results are within experimental noise. 
2) While we're editing the NPM dependencies, there are an awful lot of depreciation warnings.

**Comment by Greg-Hawkridge** [comment]
The deprecation warnings are related to "create-react-app" which creates a template application and aren't a worry because none of them are runtime dependencies for React - I've looked at alternatives - but don't see a reason for the migration effort just yet

**Comment by Greg-Hawkridge** [comment]
Also I didn't think there would be much of a difference and we're probably within margin of error on these tests

**Comment by tobyaharris** [comment]
Regardless of by how much this reduces the build time / is there further work to do, this is in no way a bad thing. Approving.

**Review by tobyaharris — APPROVED** [review]

**Pull request merged**
